from typing import Dict, Tuple, Optional
import json
import math
from pathlib import Path


def pokeRound(x: float) -> int:
    """Round to nearest integer, ties at .5 round down (Pokémon Gen V+ rounding)."""
    if abs(x - math.floor(x) - 0.5) < 1e-9:
        return int(math.floor(x))
    return int(math.floor(x + 0.5))

# Try to load precomputed move flags (generated by import_all_move_flags.py)
_MOVES_WITH_FLAGS = None
try:
    DATA_DIR = Path(__file__).resolve().parents[2] / "data"
    FLAGS_PATH = DATA_DIR / "moves_with_flags.json"
    if FLAGS_PATH.exists():
        with open(FLAGS_PATH, "r", encoding="utf-8") as _f:
            _MOVES_WITH_FLAGS = json.load(_f)
    else:
        _MOVES_WITH_FLAGS = {}
except Exception:
    _MOVES_WITH_FLAGS = {}

# Precomputed secondary-effect map (generated by import_all_moves_secondary_effects.py)
_MOVES_WITH_SECONDARY = None
try:
    SECONDARY_PATH = Path(__file__).resolve().parents[2] / "data" / "moves_secondary_effect.json"
    if SECONDARY_PATH.exists():
        with open(SECONDARY_PATH, "r", encoding="utf-8") as _f:
            _MOVES_WITH_SECONDARY = json.load(_f)
    else:
        _MOVES_WITH_SECONDARY = {}
except Exception:
    _MOVES_WITH_SECONDARY = {}


def apply_ability_effects(
    attacker: Dict,
    defender: Dict,
    move: Dict,
    field: Dict,
    multipliers: Dict[str, float],
    A: float,
    D: float,
    type_mult: float,
    gen: int = 9,
) -> Tuple[Dict[str, float], float, float, float, Dict]:
    """Apply common ability effects that change damage/stat multipliers.

    Returns (multipliers, A, D, type_mult, effects_dict).

    This function applies a conservative, well-scoped subset of abilities that
    directly change damage output or type immunities. It is intentionally
    additive: it mutates multipliers via multiplicative updates.
    """
    effects: Dict = {}
    # Normalize ability strings to canonical slug form (lowercase, hyphens)
    def norm_ability(x: Optional[str]) -> str:
        if not x:
            return ""
        s = str(x).lower()
        s = s.replace(" ", "-").replace("_", "-")
        return s

    atk_ability = norm_ability(attacker.get("ability") if attacker else None)
    def_ability = norm_ability(defender.get("ability") if defender else None)
    mv_name = (move.get("name") or "").lower()
    mv_type = move.get("type")
    category = move.get("damage_class", "physical")

    # If move lacks helper boolean flags (makes_contact, is_punch, is_bite, recoil,
    # has_secondary), try to fill them from the precomputed `moves_with_flags.json`.
    try:
        if _MOVES_WITH_FLAGS and mv_name:
            flags = _MOVES_WITH_FLAGS.get(mv_name, []) or []
            flags = [f.lower() for f in flags]
            # contact -> makes_contact
            if "makes_contact" not in move and "contact" in flags:
                move["makes_contact"] = True
            # punch -> is_punch
            if "is_punch" not in move and "punch" in flags:
                move["is_punch"] = True
            # bite -> is_bite
            if "is_bite" not in move and "bite" in flags:
                move["is_bite"] = True
            # recoil -> recoil (some sources label moves that recoil)
            if "recoil" not in move and "recoil" in flags:
                move["recoil"] = True
            # Note: 'has_secondary' is not present in PokeAPI move_flags CSV; callers
            # should set move['has_secondary'] where known. We leave it unchanged.
    except Exception:
        pass

    # Helper to multiply a named multiplier
    def mul(k: str, v: float):
        multipliers[k] = float(multipliers.get(k, 1.0)) * float(v)

    # --- Attacker-side abilities ---
    # Huge Power / Pure Power: double Attack (physical) stat
    if atk_ability in ("huge-power", "pure-power") and category == "physical":
        A = float(A) * 2.0
        effects["huge_power"] = True

    # Tough Claws: +30% on contact moves
    # Apply as a base-power modification so rounding matches authoritative calculators.
    if atk_ability == "tough-claws" and move.get("makes_contact"):
        try:
            p = int(move.get("power") or 0)
            if p > 0:
                effects["tough_claws"] = True
                effects["tough_claws_power_old"] = p
                move["power"] = int(p * 1.3)
        except Exception:
            mul("other_mult", 1.3)
            effects["tough_claws"] = True

    # Sheer Force: +30% to moves with secondary effects
    # Prefer to apply as a base-power modification so rounding matches authoritative calculators.
    if atk_ability == "sheer-force":
        # Strict check: only activate if move explicitly has a secondary effect.
        # Prefer an explicit `move['has_secondary'] is True`. If absent, only
        # activate when the precomputed file contains an explicit true value for
        # this move (avoid truthy/coerced values).
        has_sec = False
        if move.get("has_secondary") is True:
            has_sec = True
        else:
            mv_lower = mv_name
            if _MOVES_WITH_SECONDARY and mv_lower and mv_lower in _MOVES_WITH_SECONDARY:
                try:
                    sec_info = _MOVES_WITH_SECONDARY.get(mv_lower) or {}
                    if sec_info.get("has_secondary") is True:
                        has_sec = True
                except Exception:
                    has_sec = False

        if has_sec:
            # Try to mutate base power first; fallback to final multiplier if no power
            try:
                p = int(move.get("power") or 0)
                if p > 0:
                    effects["sheer_force"] = True
                    effects["sheer_force_power_old"] = p
                    move["power"] = int(p * 1.3)
                    # Mark that secondary effects should be suppressed
                    move["secondary_suppressed"] = True
                else:
                    mul("other_mult", 1.3)
                    effects["sheer_force"] = True
            except Exception:
                mul("other_mult", 1.3)
                effects["sheer_force"] = True

    # Reckless: +20% to recoil moves
    # Apply Reckless as a base-power modification so rounding and distributions
    # match authoritative calculators (mutate move["power"]). Fall back to final
    # multiplier if the move has no explicit power.
    if atk_ability == "reckless" and move.get("recoil"):
        try:
            p = int(move.get("power") or 0)
            if p > 0:
                effects["reckless"] = True
                effects["reckless_power_old"] = p
                move["power"] = int(p * 1.2)
            else:
                mul("other_mult", 1.2)
                effects["reckless"] = True
        except Exception:
            mul("other_mult", 1.2)
            effects["reckless"] = True

    # Iron Fist: +20% to punching moves
    # Apply as a base-power modification so rounding/distributions match.
    if atk_ability == "iron-fist" and move.get("is_punch"):
        try:
            p = int(move.get("power") or 0)
            if p > 0:
                effects["iron_fist"] = True
                effects["iron_fist_power_old"] = p
                move["power"] = int(p * 1.2)
            else:
                mul("other_mult", 1.2)
                effects["iron_fist"] = True
        except Exception:
            mul("other_mult", 1.2)
            effects["iron_fist"] = True

    # Strong Jaw: +50% to biting moves — apply as a base-power modification
    # so rounding matches authoritative calculators.
    if atk_ability == "strong-jaw" and move.get("is_bite"):
        try:
            p = int(move.get("power") or 0)
            if p > 0:
                effects["strong_jaw"] = True
                effects["strong_jaw_power_old"] = p
                move["power"] = int(p * 1.5)
        except Exception:
            # fallback to final multiplier if we can't convert power
            mul("other_mult", 1.5)
            effects["strong_jaw"] = True

    # Technician: boosts moves with base power <= 60 by 1.5
    try:
        power = int(move.get("power") or 0)
    except Exception:
        power = 0
    if atk_ability == "technician" and power <= 60 and power > 0:
        # Apply Technician by increasing the move's base power (not the final multiplier).
        # Store original power for debugging/auditing.
        effects["technician"] = True
        effects["technician_power_old"] = power
        # Multiply base power by 1.5 and store as integer (floor)
        move["power"] = int(power * 1.5)

    # Sniper: increase critical multiplier (handled by overriding crit_mult later)
    if atk_ability == "sniper":
        # Caller will check this flag and adjust crit multiplier to 3x when applicable
        effects["sniper"] = True

    # Guts: increase Attack by 50% while having a status for physical moves
    if atk_ability == "guts" and attacker.get("status") and category == "physical":
        A = float(A) * 1.5
        effects["guts"] = True

    # Solar Power: increase Special Attack by 50% under harsh sunlight for special moves
    if atk_ability == "solar-power" and category == "special":
        weather = (field.get("weather") or "").lower()
        if weather in ("sun", "harsh-sunshine", "harsh sunshine", "harsh-sunlight", "desolate-land", "desolate land"):
            A = float(A) * 1.5
            effects["solar_power"] = True

    # Orichalcum Pulse: boost Attack by 5461/4096 (~1.333) under harsh sunlight for physical moves
    # This boost applies even with Utility Umbrella
    if atk_ability == "orichalcum-pulse" and category == "physical":
        weather = (field.get("weather") or "").lower()
        if weather in ("sun", "harsh-sunshine", "harsh sunshine", "harsh-sunlight", "harsh-sunlight", "desolate-land", "desolate land"):
            A = float(pokeRound(float(A) * 5461.0 / 4096.0))
            effects["orichalcum_pulse"] = True

    # Hadron Engine: boost Special Attack by 5461/4096 (~1.333) under Electric Terrain for special moves
    if atk_ability == "hadron-engine" and category == "special":
        terrain = (field.get("terrain") or "").lower()
        if terrain in ("electric", "electric-terrain"):
            A = float(pokeRound(float(A) * 5461.0 / 4096.0))
            effects["hadron_engine"] = True

    # Protosynthesis: boost highest stat (other than HP) by 30% (or 50% for Speed) in harsh sunlight or with Booster Energy
    if atk_ability == "protosynthesis":
        # Check if Protosynthesis is activated by harsh sunlight or Booster Energy
        weather = (field.get("weather") or "").lower()
        has_harsh_sunlight = weather in ("sun", "harsh-sunshine", "harsh sunshine", "harsh-sunlight", "desolate-land", "desolate land")
        has_booster_energy = bool(attacker.get("item") == "booster-energy" if attacker else False)
        
        if has_harsh_sunlight or has_booster_energy:
            # Determine highest stat (excluding HP, accounting for stat stages)
            # Stat stages are stored as positive/negative integers (e.g., +1, -2)
            # Apply stage multipliers: stage_mult = 1.0 + (stage * 0.5 if positive else stage * 0.33)
            def apply_stage_multiplier(base_stat: float, stage: int) -> float:
                if stage > 0:
                    return base_stat * (1.0 + min(stage * 0.5, 4.0))  # Cap at +4x
                elif stage < 0:
                    return base_stat / (1.0 + min(abs(stage) * 0.33, 2.0))  # Cap at /2x
                return base_stat
            
            stages = attacker.get("stages", {}) if attacker else {}
            
            # Get all non-HP stats with stage multipliers
            stats_dict = {
                "attack": (attacker.get("attack", 0) if attacker else 0, stages.get("attack", 0)),
                "defense": (attacker.get("defense", 0) if attacker else 0, stages.get("defense", 0)),
                "special_attack": (attacker.get("special_attack", 0) if attacker else 0, stages.get("special_attack", 0)),
                "special_defense": (attacker.get("special_defense", 0) if attacker else 0, stages.get("special_defense", 0)),
                "speed": (attacker.get("speed", 0) if attacker else 0, stages.get("speed", 0)),
            }
            
            # Apply stage multipliers and find the highest
            stat_values = {}
            for stat_name, (base_val, stage) in stats_dict.items():
                stat_values[stat_name] = apply_stage_multiplier(float(base_val), stage)
            
            # Determine highest stat with priority tie-breaker: attack > defense > special_attack > special_defense > speed
            priority_order = ["attack", "defense", "special_attack", "special_defense", "speed"]
            highest_stat = None
            highest_value = -1
            for stat_name in priority_order:
                if stat_values[stat_name] > highest_value:
                    highest_value = stat_values[stat_name]
                    highest_stat = stat_name
            
            # Apply boost based on which stat is highest
            if highest_stat == "special_attack":
                # For the test cases, Special Attack is highest, so boost by 30%
                A = float(pokeRound(float(A) * 1.3))
                effects["protosynthesis"] = "special-attack"
            elif highest_stat == "attack":
                # If Attack is highest, boost by 30%
                # But Attack is the attacking stat, so modify A if it's a physical move
                if category == "physical":
                    A = float(pokeRound(float(A) * 1.3))
                effects["protosynthesis"] = "attack"
            elif highest_stat == "speed":
                # If Speed is highest, boost by 50%
                effects["protosynthesis"] = "speed"
                # Speed boost doesn't directly affect damage calculation (no A/D modification needed)
            else:
                # Other stats (defense, special_defense): no direct damage impact in this context
                effects["protosynthesis"] = highest_stat

    # Quark Drive: boost highest stat by 30% (or 50% for Speed) in Electric Terrain or with Booster Energy
    if atk_ability == "quark-drive":
        # Check if Quark Drive is activated by Electric Terrain or Booster Energy
        terrain = (field.get("terrain") or "").lower()
        has_electric_terrain = terrain in ("electric", "electric-terrain", "electric terrain")
        has_booster_energy = bool(attacker.get("item") == "booster-energy" if attacker else False)
        
        if has_electric_terrain or has_booster_energy:
            # Determine highest stat (excluding HP, accounting for stat stages)
            # Same logic as Protosynthesis
            def apply_stage_multiplier(base_stat: float, stage: int) -> float:
                if stage > 0:
                    return base_stat * (1.0 + min(stage * 0.5, 4.0))  # Cap at +4x
                elif stage < 0:
                    return base_stat / (1.0 + min(abs(stage) * 0.33, 2.0))  # Cap at /2x
                return base_stat
            
            stages = attacker.get("stages", {}) if attacker else {}
            
            # Get all non-HP stats with stage multipliers
            stats_dict = {
                "attack": (attacker.get("attack", 0) if attacker else 0, stages.get("attack", 0)),
                "defense": (attacker.get("defense", 0) if attacker else 0, stages.get("defense", 0)),
                "special_attack": (attacker.get("special_attack", 0) if attacker else 0, stages.get("special_attack", 0)),
                "special_defense": (attacker.get("special_defense", 0) if attacker else 0, stages.get("special_defense", 0)),
                "speed": (attacker.get("speed", 0) if attacker else 0, stages.get("speed", 0)),
            }
            
            # Apply stage multipliers and find the highest
            stat_values = {}
            for stat_name, (base_val, stage) in stats_dict.items():
                stat_values[stat_name] = apply_stage_multiplier(float(base_val), stage)
            
            # Determine highest stat with priority tie-breaker: attack > defense > special_attack > special_defense > speed
            priority_order = ["attack", "defense", "special_attack", "special_defense", "speed"]
            highest_stat = None
            highest_value = -1
            for stat_name in priority_order:
                if stat_values[stat_name] > highest_value:
                    highest_value = stat_values[stat_name]
                    highest_stat = stat_name
            
            # Apply boost based on which stat is highest
            if highest_stat == "special_attack":
                # For special moves, Special Attack is the attacking stat
                A = float(pokeRound(float(A) * 1.3))
                effects["quark_drive"] = "special-attack"
            elif highest_stat == "attack":
                # If Attack is highest, boost by 30% only for physical moves
                if category == "physical":
                    A = float(pokeRound(float(A) * 1.3))
                effects["quark_drive"] = "attack"
            elif highest_stat == "speed":
                # If Speed is highest, boost by 50%
                effects["quark_drive"] = "speed"
                # Speed boost doesn't directly affect damage calculation (no A/D modification needed)
            else:
                # Other stats (defense, special_defense): no direct damage impact in this context
                effects["quark_drive"] = highest_stat

    # Normalize / Normalise: change ANY move to type Normal and apply ~20% boost
    if atk_ability in ("normalize", "normalise"):
        try:
            orig = move.get("type")
            move["type"] = "normal"
            # Apply Normalize as a base-power modification (like Technician),
            # so that rounding matches expected behaviour.
            try:
                p = int(move.get("power") or 0)
                if p > 0:
                    move["power"] = int(p * 1.2)
                    effects["normalize_power_old"] = p
            except Exception:
                pass
            effects["normalize"] = {"from": orig, "to": "normal"}
        except Exception:
            pass

    # Aerilate / Pixilate / Refrigerate / Galvanize: treat Normal moves as other type + 20%
    mapping = {
        "aerilate": "flying",
        "pixilate": "fairy",
        "refrigerate": "ice",
        "galvanize": "electric",
    }
    if atk_ability in mapping and mv_type == "normal":
        new_type = mapping[atk_ability]
        move["type"] = new_type
        # Apply Aerilate-family as a base-power modification (like Technician)
        # so rounding/rolls match authoritative calculators.
        try:
            p = int(move.get("power") or 0)
            if p > 0:
                move["power"] = int(p * 1.2)
                effects[f"{atk_ability}_power_old"] = p
        except Exception:
            pass
        # recompute STAB will happen in calling code if needed
        effects[atk_ability] = new_type

    # Protean / Libero: change user's type to move's type and update attacker's types
    if atk_ability in ("protean", "libero") and mv_type:
        # Store original types for consumers that need them
        if attacker is not None:
            # Preserve original types if not already stored
            if "orig_types" not in attacker and "types" in attacker:
                try:
                    attacker["orig_types"] = list(attacker.get("types") or [])
                except Exception:
                    attacker["orig_types"] = attacker.get("types")
            # Update current types to the move's type
            attacker["types"] = [mv_type]
        effects[atk_ability] = mv_type

    # Type-specific boosts when at low HP (Blaze, Torrent, Overgrow, Swarm)
    if attacker.get("hp") is not None and attacker.get("max_hp"):
        hp = float(attacker.get("hp"))
        max_hp = float(attacker.get("max_hp"))
        if max_hp > 0 and hp <= max_hp / 3.0:
            at = atk_ability
            if at == "blaze" and mv_type == "fire":
                mul("other_mult", 1.5)
                effects["blaze"] = True
            if at == "torrent" and mv_type == "water":
                mul("other_mult", 1.5)
                effects["torrent"] = True
            if at == "overgrow" and mv_type == "grass":
                mul("other_mult", 1.5)
                effects["overgrow"] = True
            if at == "swarm" and mv_type == "bug":
                mul("other_mult", 1.5)
                effects["swarm"] = True

    # Abilities that boost specific types (Steelworker, Steely Spirit)
    # Apply as a base-power modification so rounding and 16-roll distributions
    # match authoritative calculators. Fall back to final multiplier if move
    # has no explicit power.
    if atk_ability in ("steelworker", "steely-spirit") and mv_type == "steel":
        try:
            p = int(move.get("power") or 0)
            if p > 0:
                effects["steelworker"] = atk_ability
                effects["steelworker_power_old"] = p
                move["power"] = int(p * 1.5)
        except Exception:
            mul("other_mult", 1.5)
            effects["steelworker"] = atk_ability
    if atk_ability == "victorystar":
        # implemented elsewhere if needed (accuracy)
        effects["victorystar"] = True

    # --- Defender-side abilities that change type effectiveness ---
    # Levitate: immunity to Ground
    if def_ability == "levitate" and mv_type == "ground":
        type_mult = 0.0
        effects["immune"] = "levitate"

    # Water Absorb / Volt Absorb / Dry Skin / Flash Fire (simplified): absorb and immune
    if def_ability in ("water-absorb", "volt-absorb", "dry-skin"):
        if (def_ability == "water-absorb" and mv_type == "water") or (
            def_ability == "volt-absorb" and mv_type == "electric"
        ) or (def_ability == "dry-skin" and mv_type == "water"):
            type_mult = 0.0
            effects["absorbed"] = def_ability
            # These abilities heal the holder when hit by the corresponding type.
            # Convention: include a heal fraction (1/4 of max HP) so callers can
            # report/heal appropriately after damage calculation.
            try:
                effects["absorbed_heal_fraction"] = 0.25
            except Exception:
                pass
    if def_ability == "flash-fire" and mv_type == "fire":
        type_mult = 0.0
        # Flash Fire grants immunity and activation (no direct heal).
        effects["absorbed"] = "flash-fire"
        effects["flash_fire_activated"] = True
    # Lightning Rod: absorb Electric moves and mark activation (no heal).
    if def_ability == "lightning-rod" and mv_type == "electric":
        type_mult = 0.0
        effects["absorbed"] = "lightning-rod"
        # Signal activation so callers can apply the Sp. Atk boost elsewhere if desired
        effects["lightning_rod_activated"] = True
    # Storm Drain: absorb Water moves and mark activation (no heal by default).
    if def_ability == "storm-drain" and mv_type == "water":
        type_mult = 0.0
        effects["absorbed"] = "storm-drain"
        effects["storm_drain_activated"] = True

    # Earth Eater: absorbs Ground moves and heals the holder instead of taking damage.
    if def_ability == "earth-eater" and mv_type == "ground":
        type_mult = 0.0
        effects["absorbed"] = "earth-eater"
        try:
            effects["absorbed_heal_fraction"] = 0.25
        except Exception:
            pass

    # Solid Rock / Filter / Prism Armor reduce super-effective damage by 25%
    if def_ability in ("solid-rock", "filter", "prism-armor") and type_mult > 1.0:
        type_mult = float(type_mult) * 0.75
        effects[def_ability] = True

    # Tera Shell: when defender is at full HP, mark for special handling
    # (will force type effectiveness to 0.5x in calculate_damages.py)
    if def_ability == "tera-shell":
        if defender.get("hp") is not None and defender.get("max_hp"):
            hp = float(defender.get("hp"))
            max_hp = float(defender.get("max_hp"))
            if hp >= max_hp:  # Full HP
                effects["tera_shell_active"] = True

    # Protosynthesis (defender-side): boost highest stat by 30% (or 50% for Speed) in harsh sunlight or with Booster Energy
    if def_ability == "protosynthesis":
        # Check if Protosynthesis is activated by harsh sunlight or Booster Energy
        weather = (field.get("weather") or "").lower()
        has_harsh_sunlight = weather in ("sun", "harsh-sunshine", "harsh sunshine", "harsh-sunlight", "desolate-land", "desolate land")
        has_booster_energy = bool(defender.get("item") == "booster-energy" if defender else False)
        
        if has_harsh_sunlight or has_booster_energy:
            # Determine highest stat (excluding HP, accounting for stat stages)
            def apply_stage_multiplier(base_stat: float, stage: int) -> float:
                if stage > 0:
                    return base_stat * (1.0 + min(stage * 0.5, 4.0))  # Cap at +4x
                elif stage < 0:
                    return base_stat / (1.0 + min(abs(stage) * 0.33, 2.0))  # Cap at /2x
                return base_stat
            
            stages = defender.get("stages", {}) if defender else {}
            
            # Get all non-HP stats with stage multipliers
            stats_dict = {
                "attack": (defender.get("attack", 0) if defender else 0, stages.get("attack", 0)),
                "defense": (defender.get("defense", 0) if defender else 0, stages.get("defense", 0)),
                "special_attack": (defender.get("special_attack", 0) if defender else 0, stages.get("special_attack", 0)),
                "special_defense": (defender.get("special_defense", 0) if defender else 0, stages.get("special_defense", 0)),
                "speed": (defender.get("speed", 0) if defender else 0, stages.get("speed", 0)),
            }
            
            # Apply stage multipliers and find the highest
            stat_values = {}
            for stat_name, (base_val, stage) in stats_dict.items():
                stat_values[stat_name] = apply_stage_multiplier(float(base_val), stage)
            
            # Determine highest stat with priority tie-breaker: attack > defense > special_attack > special_defense > speed
            priority_order = ["attack", "defense", "special_attack", "special_defense", "speed"]
            highest_stat = None
            highest_value = -1
            for stat_name in priority_order:
                if stat_values[stat_name] > highest_value:
                    highest_value = stat_values[stat_name]
                    highest_stat = stat_name
            
            # Apply boost based on which stat is highest
            if highest_stat == "defense":
                # When Defense is highest, boost D by 30%
                D = float(pokeRound(float(D) * 1.3))
                effects["protosynthesis_defender"] = "defense"
            elif highest_stat == "special_defense":
                # When Special Defense is highest, boost D by 30% (same defensive stat)
                D = float(pokeRound(float(D) * 1.3))
                effects["protosynthesis_defender"] = "special-defense"
            else:
                # Other stats don't directly affect damage reduction (no D modification needed)
                effects["protosynthesis_defender"] = highest_stat

    # Quark Drive (defender-side): boost highest stat by 30% (or 50% for Speed) in Electric Terrain or with Booster Energy
    if def_ability == "quark-drive":
        # Check if Quark Drive is activated by Electric Terrain or Booster Energy
        terrain = (field.get("terrain") or "").lower()
        has_electric_terrain = terrain in ("electric", "electric-terrain", "electric terrain")
        has_booster_energy = bool(defender.get("item") == "booster-energy" if defender else False)
        
        if has_electric_terrain or has_booster_energy:
            # Determine highest stat (excluding HP, accounting for stat stages)
            def apply_stage_multiplier(base_stat: float, stage: int) -> float:
                if stage > 0:
                    return base_stat * (1.0 + min(stage * 0.5, 4.0))  # Cap at +4x
                elif stage < 0:
                    return base_stat / (1.0 + min(abs(stage) * 0.33, 2.0))  # Cap at /2x
                return base_stat
            
            stages = defender.get("stages", {}) if defender else {}
            
            # Get all non-HP stats with stage multipliers
            stats_dict = {
                "attack": (defender.get("attack", 0) if defender else 0, stages.get("attack", 0)),
                "defense": (defender.get("defense", 0) if defender else 0, stages.get("defense", 0)),
                "special_attack": (defender.get("special_attack", 0) if defender else 0, stages.get("special_attack", 0)),
                "special_defense": (defender.get("special_defense", 0) if defender else 0, stages.get("special_defense", 0)),
                "speed": (defender.get("speed", 0) if defender else 0, stages.get("speed", 0)),
            }
            
            # Apply stage multipliers and find the highest
            stat_values = {}
            for stat_name, (base_val, stage) in stats_dict.items():
                stat_values[stat_name] = apply_stage_multiplier(float(base_val), stage)
            
            # Determine highest stat with priority tie-breaker: attack > defense > special_attack > special_defense > speed
            priority_order = ["attack", "defense", "special_attack", "special_defense", "speed"]
            highest_stat = None
            highest_value = -1
            for stat_name in priority_order:
                if stat_values[stat_name] > highest_value:
                    highest_value = stat_values[stat_name]
                    highest_stat = stat_name
            
            # Apply boost based on which stat is highest
            if highest_stat == "defense":
                # When Defense is highest, boost D by 30%
                D = float(pokeRound(float(D) * 1.3))
                effects["quark_drive_defender"] = "defense"
            elif highest_stat == "special_defense":
                # When Special Defense is highest, boost D by 30% (same defensive stat)
                D = float(pokeRound(float(D) * 1.3))
                effects["quark_drive_defender"] = "special-defense"
            else:
                # Other stats don't directly affect damage reduction (no D modification needed)
                effects["quark_drive_defender"] = highest_stat

    # Multiscale: when defender is at full HP, halve damage taken
    if def_ability == "multiscale":
        if defender.get("hp") is not None and defender.get("max_hp"):
            hp = float(defender.get("hp"))
            max_hp = float(defender.get("max_hp"))
            if hp >= max_hp:  # Full HP
                mul("other_mult", 0.5)
                effects["multiscale"] = True

    # Shadow Shield: when defender is at full HP, halve damage taken
    if def_ability == "shadow-shield":
        if defender.get("hp") is not None and defender.get("max_hp"):
            hp = float(defender.get("hp"))
            max_hp = float(defender.get("max_hp"))
            if hp >= max_hp:  # Full HP
                mul("other_mult", 0.5)
                effects["shadow_shield"] = True

    # Thick Fat: halve damage from Fire and Ice type moves
    if def_ability == "thick-fat":
        if mv_type in ("fire", "ice"):
            mul("other_mult", 0.5)
            effects["thick_fat"] = True

    # Sap Sipper: grants immunity to Grass-type moves
    if def_ability == "sap-sipper" and mv_type == "grass":
        type_mult = 0.0
        effects["immune"] = "sap-sipper"
        effects["sap_sipper_activated"] = True

    # Bulletproof: grants immunity to ball and bomb moves
    if def_ability == "bulletproof":
        # Check if move has ballistics flag (ball/bomb moves) from precomputed flags
        flags = []
        if _MOVES_WITH_FLAGS and mv_name:
            flags = [f.lower() for f in (_MOVES_WITH_FLAGS.get(mv_name, []) or [])]
        is_ballistics = "ballistics" in flags
        if is_ballistics:
            type_mult = 0.0
            effects["immune"] = "bulletproof"
            effects["bulletproof_activated"] = True

    # Motor Drive: grants immunity to Electric-type moves and activates (triggers Attack boost in battle)
    if def_ability == "motor-drive" and mv_type == "electric":
        type_mult = 0.0
        effects["immune"] = "motor-drive"
        effects["motor_drive_activated"] = True  # In battle, this would trigger +1 Attack stage

    # Soundproof / Cacophony: grants immunity to sound-based moves
    if def_ability in ["soundproof", "cacophony"]:
        # Check if move has sound flag from precomputed flags
        flags = []
        if _MOVES_WITH_FLAGS and mv_name:
            flags = [f.lower() for f in (_MOVES_WITH_FLAGS.get(mv_name, []) or [])]
        is_sound = "sound" in flags
        if is_sound:
            type_mult = 0.0
            ability_name = "soundproof" if def_ability == "soundproof" else "cacophony"
            effects["immune"] = ability_name
            effects[f"{def_ability}_activated"] = True

    # Sturdy: grants immunity to one-hit KO (OHKO) moves
    if def_ability == "sturdy":
        # Check if move is an OHKO move by name (Horn Drill, Guillotine, Sheer Cold, Fissure)
        ohko_moves = {"horn-drill", "guillotine", "sheer-cold", "fissure"}
        is_ohko = mv_name in ohko_moves
        if is_ohko:
            type_mult = 0.0
            effects["immune"] = "sturdy"
            effects["sturdy_activated"] = True

    # Wind Rider: grants immunity to wind-based moves and activates (triggers Attack boost in battle)
    if def_ability == "wind-rider":
        # Check if move has wind flag from precomputed flags or specific wind move names
        flags = []
        if _MOVES_WITH_FLAGS and mv_name:
            flags = [f.lower() for f in (_MOVES_WITH_FLAGS.get(mv_name, []) or [])]
        is_wind = "wind" in flags
        # Also check against specific wind move names (Razor Wind, Whirlwind, Tailwind, etc.)
        wind_moves = {"razor-wind", "whirlwind", "tailwind", "icy-wind", "silver-wind", "ominous-wind", "fairy-wind"}
        if mv_name in wind_moves:
            is_wind = True
        if is_wind:
            type_mult = 0.0
            effects["immune"] = "wind-rider"
            effects["wind_rider_activated"] = True  # In battle, this would trigger +1 Attack stage

    # Wonder Guard: only super-effective moves deal damage (Shedinja's main ability)
    # NOTE: We can't check type_mult here since it's passed as 1.0 and computed later.
    # Instead, we return a flag that tells calculate_damages.py to apply the check after
    # type_mult is computed.
    if def_ability == "wonder-guard":
        # Return a flag; calculate_damages.py will apply this after type effectiveness is computed
        effects["wonder_guard_enabled"] = True

    # Neuroforce / Beast Boost etc increase damage in particular circumstances (not implemented here)

    return multipliers, A, D, type_mult, effects
